export const ADD_CONTENDER = 'ADD_CONTENDER';
export const CONTENDERS_LOADING = 'CONTENDERS_LOADING';
export const CONTENDERS_FAILED = 'CONTENDERS_FAILED';
export const SHOW_CONTENDERS = 'SHOW_CONTENDERS';

export const ADD_HEATRECORD = 'ADD_HEATRECORD';
// export const RANKING_FAILED = 'RANKING_FAILED';
// export const RANKING_LOADING = 'RANKING_LOADING';
